version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies for Stack
          keys:
            - v1-stack-{{ checksum "stack.yaml.lock" }}-{{ checksum "package.yaml" }}
            - v1-stack-{{ checksum "stack.yaml.lock" }}-
      - run: stack --no-terminal setup
      - run: stack --no-terminal --jobs 1 install hlint
      - run: stack --no-terminal --jobs 1 test --no-run-tests
      - save_cache:
          name: Cache Dependencies for Stack
          key: v1-stack-{{ checksum "stack.yaml.lock" }}-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack
            - .stack-work
      - run: hlint .
      - run: stack --no-terminal test
